### PR TITLE
Bugfix in eupdata.sty

### PR DESCRIPTION
**Pull request by CFGrote**
This caused me some headache in getting the example to work. Using the makefile, it gets ignored, hence went unnoticed for a while.
not sure why c8c2cca is suddenly my commit. 

another issue with the examples: they interfere with local tex files if TEXINPUTS=$PATH_TO_LATEX_PROPOSAL:$TEXINPUTS is used to include the class, since this also exposes the example sources to tex.

### CODE REVIEW

**Comment by kohlhase** [comment]
Thanks a lot for debugging this. However, there is a problem with the pull request. 

It seems that commit 85f0043de052e9df74dd1929f5924af40ee4f944 got reverted (changed only in `eupdata.sty` which gets generated from `euproposal.dtx` and was therefore overwritten. So only the updates on the dates are in the pull request. 
I will fix this in my copy and then commit and we can remove the PR.

**Comment by kohlhase** [comment]
> another issue with the examples: they interfere with local tex files if TEXINPUTS=$PATH_TO_LATEX_PROPOSAL:$TEXINPUTS is used to include the class, since this also exposes the example sources to tex.

I am not sure I understand. Can you make an issue of this?

**Comment by CFGrote** [comment]
sorry for being confusing.
i guess what i'm saying is that when setting my TEXINPUTS to
LaTeX-proposal//, any \input{propB} (as an example) would also see the
propB.tex in the examples directory under LaTeX-proposal//. While this
may still be acceptable for sources present in $PWD (tex should find
these first) it poses a risk if it comes to the autogenerated .pdata and
.delivs . If sth goes wrong in generating the .pdata (as it did due to
the eupdata.sty bug, tex will then take the .pdata in the examples dir.
For someone starting a new proposal from a given example, this can be
very hard to detect.

i guess for this reason, the examples are not included in the ctan
package (make ctan).

hope that's clearer now.

carsten

On Wed, Nov 29, 2017 at 12:12:57PM +0000, Michael Kohlhase wrote:
> > another issue with the examples: they interfere with local tex files if TEXINPUTS=$PATH_TO_LATEX_PROPOSAL:$TEXINPUTS is used to include the class, since this also exposes the example sources to tex.
>
> I am not sure I understand. Can you make an issue of this?
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/KWARC/LaTeX-proposal/pull/34#issuecomment-347842412

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Director: Prof. Dr. Robert Feidenhans'l

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by kohlhase** [comment]
> another issue with the examples: they interfere with local tex files if TEXINPUTS=$PATH_TO_LATEX_PROPOSAL:$TEXINPUTS is used to include the class, since this also exposes the example sources to tex.

thanks for the clarification. I made an issue (#35) out of this; I also intend to fix it soon

**Comment by CFGrote** [comment]
ok, thanks.

c.

**Pull request closed without merging**
